# Generated by Django 6.0.1 on 2026-01-28 10:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayed_items',
            name='display_color',
            field=colorfield.fields.ColorField(default='#575757', image_field=None, max_length=25, samples=None),
        ),
    ]
